name: Deploy Infrastructure (Manual)

on:
  workflow_dispatch:  # ✅ manual trigger only

jobs:
  deploy:
    name: Terraform Apply (Dev)
    runs-on: ubuntu-latest
    environment:
      name: dev-deploy
      url: https://portal.azure.com/

    defaults:
      run:
        working-directory: ./infra/envs/dev 

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TF_VAR_tenant_id: ${{ secrets.ARM_TENANT_ID }}
      TF_LOG: INFO
      TF_LOG_PATH: terraform-debug.log

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="dev.tfvars"
